### ISSUE TITLE
Compilation problem

### ISSUE THREAD

**Issue by manio** [ssalonen/cec-alsa-sync#7]
## Bug description

Hi. I am trying to compile but I've got the following error:
```
[...]
  = note: /usr/bin/ld: /usr/src/cec-alsa-sync/target/debug/deps/libcec_rs-60b5991009b004f6.rlib(cec_rs-60b5991009b004f6.cec_rs.2b43c085-cgu.2.rcgu.o): in function `cec_rs::CecConnectionCfg::open':
          /home/manio/.cargo/registry/src/github.com-1ecc6299db9ec823/cec-rs-3.0.0/src/lib.rs:1201: undefined reference to `libcec_enable_callbacks'
          collect2: error: ld returned 1 exit status
          
  = help: some `extern` functions couldn't be found; some native libraries may need to be installed or have their path specified
  = note: use the `-l` flag to specify native libraries to link
  = note: use the `cargo:rustc-link-lib` directive to specify the native libraries to link with Cargo (see https://doc.rust-lang.org/cargo/reference/build-scripts.html#cargorustc-link-libkindname)

warning: `cec-alsa-sync` (bin "cec-alsa-sync") generated 3 warnings
error: could not compile `cec-alsa-sync` due to previous error; 3 warnings emitted
```
## Environment

- OS: Arch Linux

Is it a problem of too new libcec? Currently in arch it is `6.0.2-1`

**Comment by ssalonen** [comment]
It looks likely yes.... 

libcec C headers have the following:
[
#if CEC_LIB_VERSION_MAJOR >= 5
extern DECLSPEC int libcec_set_callbacks(libcec_connection_t connection, CEC_NAMESPACE ICECCallbacks* callbacks, void* cbParam);
extern DECLSPEC int libcec_disabled_callbacks(libcec_connection_t connection);
#else
extern DECLSPEC int libcec_enable_callbacks(libcec_connection_t connection, void* cbParam, CEC_NAMESPACE ICECCallbacks* callbacks);
#endif](https://github.com/Pulse-Eight/libcec/blob/76551ea1dd9a55f0ce1533e440dc12dbc594f7ba/include/cecc.h#L56-L61)

Probably `cec-rs` should offer feature flags (or autodetect?) or similar to specify libcec version. What would be the best practice on this?

**Comment by ssalonen** [comment]
https://kornel.ski/rust-sys-crate

Recommends to have feature flags for minor differences like we have here, this seems to be the practice with popular sys crates as well

> Different major versions
If differences between major versions of the C library are small (e.g. only new functions added, or just a couple of struct fields changed), then you could try to automatically adapt to the version or use Cargo features to enable the new features (e.g. mozjpeg-sys supports different ABI versions, clang-sys has features for LLVM versions).

> If versions of the C library are totally different and incompatible, then either have separate crates (foo1-sys & foo2-sys) or at least use different major versions of your sys crate for different major versions of the C library, so that Cargo will know that they're not compatible.


Would you like to make a PR?

We probably should extend CI tests to test compilation against both libcec4 and libcec5/6.

**Comment by manio** [comment]
Hi
Thanks for your investigation :)
> Would you like to make a PR?

Of course I can try to do it... but if it is a piece of cake for you, I'd rather leave it to you :)

**Comment by ssalonen** [comment]
Heh :) probably it is not as quick I originally thought as there many moving parts, for example cbindgen code generation (both in libcec-sys lib.rs and cec-rs enum.rs), supporting compilation of vendored sources in libcec-sys and overall understanding any other possible changes (e.g. In data types and enum values). I put these as comments in libcec-sys issue 

Should probably start with a rough design on the needed changes

I am quite limited with time nowadays so it might take some time from my side to work on it.

As a workaround, do you have option to install the older version in arch?

**Comment by manio** [comment]
Yeah, I'll install the older one, thank you!

**Comment by ssalonen** [comment]
@manio  appreciate if you can test with cec-alsa-sync 2.0.0? It should now work with libcec6.

```
❯ ldd ./target/release/cec-alsa-sync                                                                                                                                             ✘ 130 master
	SNIP
	libcec.so.6 => /lib64/libcec.so.6 (0x00007f196a95e000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f196a943000)
	libp8-platform.so.2 => /lib64/libp8-platform.so.2 (0x00007f196a935000)
	SNIP

```

**Comment by manio** [comment]
@ssalonen 
Confirmed - it's now compiling and working fine!
Much thanks! :)
